runmode: prev
appport: 8010
alloworigins:
  - https://www.1024cx.top
  - http://localhost:8090

dev:
  mysql:
    host:     127.0.0.1
    port:     3306
    user:     root
    password: 1
  redis:
    host:     127.0.0.1
    port:     6379
    password:
    db:

prev:
  mysql:
    host:      192.168.0.117
    port:      3306
    user:      root
    password:  1
  redis:
    host:      192.168.0.117
    port:      6379
    password:
    db:

prod:
  mysql:
    host:      172.16.218.30
    port:      3306
    user:      test4
    password:  test4
  redis:
    host:      172.16.218.30
    port:      6379
    password:
    db: