runmode: dev
appport: 50052

dev:
  goodsserviceaddr: 127.0.0.1:50051
  mysql:
    host:     127.0.0.1
    port:     3306
    user:     root
    password: 1
  redis:
    host:     127.0.0.1
    port:     6379
    password:
    db:

prev:
  goodsserviceaddr: 127.0.0.1:50051
  mysql:
    host:      192.168.0.117
    port:      3306
    user:      root
    password:  1
  redis:
    host:      192.168.0.117
    port:      6379
    password:
    db:

prod:
  goodsserviceaddr: goods:50051
  mysql:
    host:      172.16.218.30
    port:      3306
    user:      test4
    password:  test4
  redis:
    host:      172.16.218.30
    port:      6379
    password:
    db: